[theme]
base = "light"

# Accent color
primaryColor = "#0F766E"

# Main background
backgroundColor = "#F8FAFC"

# Cards/sidebar
secondaryBackgroundColor = "#E2E8F0"

# Text
textColor = "#111827"

font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true
